# Generated by Django 5.0 on 2024-01-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_category_image_alter_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='media/dishes/blog-4.jpg', upload_to='media/dishes/'),
        ),
    ]
