# Generated by Django 5.0 on 2024-02-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_tablebooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableBooking',
        ),
    ]
